"""2nd  revision

Revision ID: 0f30c8bcb0a0
Revises: 6aaa52d8fc2d
Create Date: 2023-06-22 09:37:23.565538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f30c8bcb0a0'
down_revision = '6aaa52d8fc2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###
