"""2nd  revision

Revision ID: 6aaa52d8fc2d
Revises: c2c5fe540549
Create Date: 2023-06-22 09:35:26.734399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aaa52d8fc2d'
down_revision = 'c2c5fe540549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_count', sa.Integer(), nullable=True))
        batch_op.drop_column('preview_url')
        batch_op.drop_column('open_library_id')
        batch_op.drop_column('excerpts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excerpts', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('open_library_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('preview_url', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('rating_count')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
