"""3rd  revision

Revision ID: b8eb40e1d773
Revises: 0f30c8bcb0a0
Create Date: 2023-06-22 15:55:13.041065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8eb40e1d773'
down_revision = '0f30c8bcb0a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subjects', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('subjects')

    # ### end Alembic commands ###
