"""2nd revision

Revision ID: ba04f3ff5a2c
Revises: 5c7649c63a4a
Create Date: 2023-06-15 08:12:11.521241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba04f3ff5a2c'
down_revision = '5c7649c63a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('excerpts', sa.String(), nullable=True),
    sa.Column('preview_url', sa.String(), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('open_library_id', sa.String(), nullable=True),
    sa.Column('cover', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language')
        batch_op.drop_column('isbn')
        batch_op.drop_column('excerpts')
        batch_op.drop_column('cover')
        batch_op.drop_column('open_library_id')
        batch_op.drop_column('title')
        batch_op.drop_column('publisher')
        batch_op.drop_column('publish_date')
        batch_op.drop_column('description')
        batch_op.drop_column('preview_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_url', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('publish_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('publisher', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('open_library_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('cover', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('excerpts', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('isbn', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.VARCHAR(), nullable=True))

    op.drop_table('books')
    # ### end Alembic commands ###
